version: '3.8'
services:
  web:
    build: .
    container_name: adhdpapi-web
    ports:
      - "5000:5000"
    env_file: .env
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - TWILIO_ACCOUNT_SID=${TWILIO_ACCOUNT_SID}
      - TWILIO_AUTH_TOKEN=${TWILIO_AUTH_TOKEN}
      - TWILIO_NUMBER=${TWILIO_NUMBER}
      - RECIPIENT_PHONE=${RECIPIENT_PHONE}
      - CELERY_BROKER_URL=${CELERY_BROKER_URL}
      - CELERY_RESULT_BACKEND=${CELERY_RESULT_BACKEND}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    depends_on:
      - redis

  celery_worker:
    build: .
    container_name: adhdpapi-celery-worker
    command: celery -A celery_app worker --loglevel=info
    env_file: .env
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - TWILIO_ACCOUNT_SID=${TWILIO_ACCOUNT_SID}
      - TWILIO_AUTH_TOKEN=${TWILIO_AUTH_TOKEN}
      - TWILIO_NUMBER=${TWILIO_NUMBER}
      - RECIPIENT_PHONE=${RECIPIENT_PHONE}
      - CELERY_BROKER_URL=${CELERY_BROKER_URL}
      - CELERY_RESULT_BACKEND=${CELERY_RESULT_BACKEND}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    depends_on:
      - redis

  celery_beat:
    build: .
    container_name: adhdpapi-celery-beat
    command: celery -A celery_app beat --loglevel=info
    env_file: .env
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - TWILIO_ACCOUNT_SID=${TWILIO_ACCOUNT_SID}
      - TWILIO_AUTH_TOKEN=${TWILIO_AUTH_TOKEN}
      - TWILIO_NUMBER=${TWILIO_NUMBER}
      - RECIPIENT_PHONE=${RECIPIENT_PHONE}
      - CELERY_BROKER_URL=${CELERY_BROKER_URL}
      - CELERY_RESULT_BACKEND=${CELERY_RESULT_BACKEND}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    depends_on:
      - redis

  redis:
    image: redis:6.0
    container_name: adhdpapi-redis
