version: '3.8'
services:
  web:
    build: .
    container_name: adhdpapi-web
    ports:
      - "5000:5000"
    environment:
      - SECRET_KEY=secret key
      - TWILIO_ACCOUNT_SID=AC529e884c7fc116040ee424090d74aa97
      - TWILIO_AUTH_TOKEN=204fc0dcf7f9d9d878bfa4815cd09d69
      - TWILIO_NUMBER=whatsapp:+14155238886
      - RECIPIENT_PHONE=whatsapp:+14058333638
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - OPENAI_API_KEY=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
    depends_on:
      - redis

  celery_worker:
    build: .
    container_name: adhdpapi-celery-worker
    command: celery -A celery_app worker --loglevel=info
    environment:
      - SECRET_KEY=secret key
      - TWILIO_ACCOUNT_SID=AC529e884c7fc116040ee424090d74aa97
      - TWILIO_AUTH_TOKEN=204fc0dcf7f9d9d878bfa4815cd09d69
      - TWILIO_NUMBER=whatsapp:+14155238886
      - RECIPIENT_PHONE=whatsapp:+14058333638
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - OPENAI_API_KEY=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
    depends_on:
      - redis

  celery_beat:
    build: .
    container_name: adhdpapi-celery-beat
    command: celery -A celery_app beat --loglevel=info
    environment:
      - SECRET_KEY=secret key
      - TWILIO_ACCOUNT_SID=AC529e884c7fc116040ee424090d74aa97
      - TWILIO_AUTH_TOKEN=204fc0dcf7f9d9d878bfa4815cd09d69
      - TWILIO_NUMBER=whatsapp:+14155238886
      - RECIPIENT_PHONE=whatsapp:+14058333638
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - OPENAI_API_KEY=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
    depends_on:
      - redis

  redis:
    image: redis:6.0
    container_name: adhdpapi-redis










